# (paste the YAML above)
name: Manual Astro Sync

on:
  workflow_dispatch: {}   # <- this line fixes the trigger

permissions:
  contents: read

concurrency:
  group: manual-sync
  cancel-in-progress: true

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    env:
      ROOT: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Bubble → Files sync (prebuilt HTML)
        env:
          BUBBLE_BASE_URL: ${{ secrets.BUBBLE_BASE_URL }}
        run: |
          : "${BUBBLE_BASE_URL:=https://stackable.club/version-test/api/1.1/obj}"
          pnpm --filter scripts run build:sync
          pnpm --filter scripts run sync

      - name: Ensure public/ exists (Astro fallback)
        run: |
          if [ ! -f "projects/study-in--japan/public/index.html" ]; then
            pnpm --filter "study-in--japan" run build
            rsync -a --delete projects/study-in--japan/dist/ projects/study-in--japan/public/
          fi

      - name: Verify generated files
        run: |
          COUNT=$(find projects/study-in--japan/public -type f | wc -l | tr -d ' ')
          echo "File count in public/: $COUNT"
          find projects/study-in--japan/public -type f | head -n 30
          if [ "$COUNT" -le 0 ]; then echo "No files to deploy"; exit 1; fi

      - name: Zip public/
        run: |
          cd projects/study-in--japan/public
          zip -qr "${ROOT}/site.zip" .

      - name: Deploy ZIP to Netlify (production)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID_JAPAN: ${{ secrets.NETLIFY_SITE_ID_JAPAN }}
        run: |
          test -n "$NETLIFY_AUTH_TOKEN" && test -n "$NETLIFY_SITE_ID_JAPAN" || { echo "Missing NETLIFY secrets"; exit 1; }
          RESP=$(curl -sS -X POST \
            -H "Authorization: Bearer ${NETLIFY_AUTH_TOKEN}" \
            -H "Content-Type: application/zip" \
            --data-binary "@${ROOT}/site.zip" \
            "https://api.netlify.com/api/v1/sites/${NETLIFY_SITE_ID_JAPAN}/deploys")
          echo "$RESP" | python3 - <<'PY'
import sys, json
d = json.load(sys.stdin)
print("Deploy id:", d.get("id"))
print("Deploy URL:", d.get("url") or d.get("ssl_url"))
print("Admin deploy page:", d.get("admin_url"))
PY
