name: Manual Astro Sync

on:
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: manual-sync
  cancel-in-progress: true

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    env:
      BUBBLE_BASE_URL: ${{ secrets.BUBBLE_BASE_URL || 'https://stackable.club/version-test/api/1.1/obj' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with: { version: 9 }

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Bubble → Files sync (prebuilt HTML → projects/study-in--japan/public)
        run: |
          pnpm --filter scripts run build:sync
          pnpm --filter scripts run sync

      - name: Ensure public/ exists (fallback to dist → public)
        run: |
          if [ ! -f "projects/study-in--japan/public/index.html" ]; then
            echo "public/ missing — building workspace 'study-in--japan' and mirroring dist → public"
            pnpm --filter "study-in--japan" run build
            rsync -a --delete projects/study-in--japan/dist/ projects/study-in--japan/public/
          fi

      - name: Show sample of generated files
        run: |
          echo "Count:"; find projects/study-in--japan/public -type f | wc -l
          echo "Sample:"; find projects/study-in--japan/public -type f | head -n 25

      # ---- DIRECT ZIP DEPLOY to Netlify (no CLI, no monorepo detection) ----
      - name: Zip public/
        run: |
          cd projects/study-in--japan/public
          zip -qr "${GITHUB_WORKSPACE}/site.zip" .

      - name: Deploy ZIP to Netlify (production)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID_JAPAN: ${{ secrets.NETLIFY_SITE_ID_JAPAN }}
        run: |
          set -euo pipefail
          RESP=$(curl -sS -X POST \
            -H "Authorization: Bearer ${NETLIFY_AUTH_TOKEN}" \
            -H "Content-Type: application/zip" \
            --data-binary "@${GITHUB_WORKSPACE}/site.zip" \
            "https://api.netlify.com/api/v1/sites/${NETLIFY_SITE_ID_JAPAN}/deploys")
          echo "$RESP" | python3 - <<'PY'
import sys, json
d = json.load(sys.stdin)
print("Deploy id:", d.get("id"))
print("Deploy URL:", d.get("url") or d.get("ssl_url"))
print("Admin deploy page:", d.get("admin_url"))
PY
